// Main layour wrapper
import type { Metadata } from "next";
import "../../styles/global.css";

export const metadata: Metadata = {
  title: "EOS CODE LAB",
  description: "TODO: Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        
        {children}
      </body>
    </html>
  );
}
